export const REAL_ORDERS = [
  { name: "Muh. Fauzan Arkas", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Ahmad zulkarnain", training: "Mikrotik MTCNA + Exam", type: "online" },
  { name: "Junswhandy", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Mulyo ogiyanto", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Dimaz Yasa Pramudya", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Muhamad Danang Jasin", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "M Ilham Saputra", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Nazar Iman Ismail", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "WISNU CAHYA RAMADHAN", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Zen Widodo", training: "Mikrotik MTCNA + Exam", type: "online" },
  { name: "Yonas Hadi Saputra", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Afif Diapari Maaruf Lubis", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Zulkifli", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Michael Davila", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Rangga Haikal Fayadh Azis", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Rey Ardan Maulana", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Rezcky Septian Hartono", training: "Mikrotik MTCNA + Exam", type: "online" },
  { name: "Muhammad Ilham Rizqi", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "M. Ramadhansyah", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Zikrabi Hidayat", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "MHD WILDAN", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Ramdhani Sakti", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Muhammad Rafli Adhianto", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Husam Muhammad", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Moh Zulva Karisma", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Aldo Ageng Prabowo", training: "Mikrotik MTCNA + Exam", type: "online" },
  { name: "Anggiet Harjo Baskoro Bonari", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Ezekiel Furqon Patongai", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Althaf Dhia Hamid", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "AHMAD BAIHAQI SYAWALUDDIN", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Akhmat Safrudin", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Fernanda Aziz Ashidqi", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Muhammad Alfin Triansyah Putra", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Muhajir", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Zakariah", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Muhammad Salman", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Akhdan Arif Prayoga", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Mailda Fajrian", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Wahyu Mas Novianto", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "ROLAND FERNANDO", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Nirman Salim", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Bogi Darmawan", training: "Mikrotik MTCNA + Exam", type: "online" },
  { name: "Zaenal Arifin", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Nouval Hisyam Wahono", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Rafka Nadimsyah Rasidi", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Danang Wahyu Pambudi", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Eky Pambudi Syiamtoni", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Melanda Tiara Komala S", training: "Mikrotik MTCNA + Exam", type: "offline" },
  { name: "Muhammad Reinaldy Gunawan", training: "Mikrotik MTCNA + Exam", type: "offline" },
];

export const CURRICULUM = [
  "Introduction Module: MikroTik, WinBox, RouterOS CLI",
  "DHCP: Server & Client configuration, Address Management",
  "Bridging: Bridging concepts, Wireless Bridging",
  "Routing: Static routing, Routing table, Default route",
  "Wireless: Access Point, Client, Security Profiles",
  "Firewall: Filter rules, Address lists, NAT, Connection tracking",
  "QoS: Simple Queue, PCQ, Traffic shaping",
  "Tunnels: PPP, PPTP, L2TP, PPPoE configuration",
  "Misc: RouterOS Tools, Dude, Torch, Monitoring"
];
